language: java

jdk: openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: lorenzobettini-github
    token:
      secure: $SONAR_TOKEN

# skip installation step
install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

env: DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - mvn -f com.examples.school/pom.xml clean verify -Pjacoco sonar:sonar
